### ISSUE TITLE
framework not found Pods_AffdexMe

### ISSUE THREAD

**Issue by foocp** [Affectiva/affdexme-osx#3]
it won't build: 

> ld: framework not found Pods_AffdexMe
clang: error: linker command failed with exit code 1 (use -v to see invocation)

probably just a bad link - that directory is in "Target Support Files" and I think it's not referenced properly?!

**Comment by stephen-phillips-affectiva** [comment]
Hi, this version of AffdexMe now supports CocoaPods.  After downloading the project, run "pod install" in the top-level AffdexMe directory, then make sure to open the .xcworkspace file in Xcode instead of the .xcodeproj file.  This should result in a successful build -- please let us know if you encounter any other issues.

**Comment by foocp** [comment]
Thanks! running the .xcworkspace file did it. Already got CocoaPod installed, btw. I had no need to do a `rm -rf Pods` as specified in your readme.

**Comment by stephen-phillips-affectiva** [comment]
Thanks for the additional information and we're glad you were able to get this project to build successfully.  For a first-time install there's no need to do `rm -rf Pods` before `pod install` so we'll update our documentation accordingly.
